[project]
name = 'trace-bug'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.caller]
path = 'contracts/caller.clar'
clarity_version = 2
epoch = 2.4

[contracts.impl]
path = 'contracts/impl.clar'
clarity_version = 2
epoch = 2.4

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
